"""Round 179 roster: the 197 new enemies - sprite slug, name, rank, colors, deck theme, extra quest tags.
Ranks: A = Apprentice (Common), D = Adept (Uncommon), M = Master (Rare), X = Archmage (Mythic).
Theme keys are defined in deckgen179.py (THEMES)."""

ROSTER = [
    # ---------------------------------------------------------------- Ragnarok Online sheets (124)
    ("ro_effects_sorceror_summons_tera_iii", "Earthcore Colossus", "M", "RGW", "elemental", ["Stone", "Large"]),
    ("ro_homunculus_eira", "Galewhisper Sylph", "D", "GWU", "faerie", ["Wind", "Flying"]),
    ("ro_homunculus_eleanor", "Snowmane Brawler", "D", "URW", "monk", ["Fighter"]),
    ("ro_homunculus_filir", "Duskfeather Owlet", "A", "WU", "bird", ["Small", "Flying"]),
    ("ro_homunculus_filir_alternate_evolved", "Sunplume Phoenix", "M", "URW", "phoenix", ["Fire", "Flying"]),
    ("ro_homunculus_filir_evolved", "Skyhall Harrier", "D", "GWU", "bird", ["Flying"]),
    ("ro_homunculus_vanilmirth_alternate", "Gazestalk Ooze", "A", "UG", "ooze", ["Small"]),
    ("ro_homunculus_vanilmirth_alternate_evolved", "Mossmane Shambler", "D", "G", "plant", ["Nature"]),
    ("ro_homunculus_vanilmirth_evolved", "Geode Slug", "M", "URW", "elemental", ["Stone"]),
    ("ro_nidhogger_s_shadow", "Shade of the Rootwyrm", "X", "UBR", "dragon", ["Flying", "Mythical"]),
    ("ro_nightmare_ancient_mummy", "Tombwrapped Ancient", "M", "WUB", "mummy", ["Unholy"]),
    ("ro_nightmare_minorous", "Anvilhorn Minotaur", "M", "R", "minotaur", ["Warrior", "Large"]),
    ("ro_obeaune", "Coraltress Siren", "D", "U", "merfolk", ["Swimming"]),
    ("ro_odium_of_thanatos", "Odium of the Last Spire", "X", "WUB", "horror", ["Unholy", "Evil"]),
    ("ro_orc_archer", "Grimtusk Bowman", "A", "R", "orc", ["Archer"]),
    ("ro_orc_baby", "Orcling Rascal", "A", "R", "orc", ["Small"]),
    ("ro_orc_lady", "Grimtusk Matron", "D", "RGW", "orc", ["Warrior"]),
    ("ro_orc_lord", "Warlord of the Grimtusk", "X", "RWB", "orc", ["Warrior", "Leader"]),
    ("ro_orc_santa", "Frostcloak Marauder", "D", "URW", "orc", ["Warrior", "Snow"]),
    ("ro_orc_skeleton", "Bonetusk Legionnaire", "D", "RWB", "skeleton", ["Orc"]),
    ("ro_orc_warrior", "Grimtusk Shieldbearer", "D", "R", "orc", ["Warrior"]),
    ("ro_orc_zombie", "Rotgut Orc", "A", "BR", "zombie", ["Orc"]),
    ("ro_osiris", "Neferu, the Sealed King", "X", "WUB", "mummy", ["Leader", "Legendary"]),
    ("ro_parus", "Sackbeak Peddler", "D", "U", "rogue", ["Bird", "Thief"]),
    ("ro_pasana", "Sandveil Blademaster", "M", "URW", "warrior", ["Fire"]),
    ("ro_payon_soldier", "Lantern Ward Spearman", "A", "W", "soldier", ["Human"]),
    ("ro_payon_soldier_alternate", "Lantern Ward Sergeant", "D", "W", "soldier", ["Human"]),
    ("ro_peco_peco", "Duneflock Runner", "A", "GW", "bird", ["Domesticated"]),
    ("ro_pere", "Pale Foundling", "D", "WU", "spirit", ["Ghost"]),
    ("ro_permeter", "Mossback Tortoise", "A", "UG", "turtle", ["Nature"]),
    ("ro_pest", "Shellhusk Crawler", "A", "G", "worm", ["Small"]),
    ("ro_petite_ground", "Mossfang Drakeling", "D", "RG", "dragon", ["Small"]),
    ("ro_petite_sky", "Frostcrest Drakeling", "D", "U", "drake", ["Flying", "Snow"]),
    ("ro_phendark", "Masked Ironbrute", "M", "R", "giant", ["Large"]),
    ("ro_piere", "Thornwing Mantis", "D", "G", "insect", ["Flying"]),
    ("ro_pinguicula", "Blossomtrap Dryad", "M", "GWU", "plant", ["Nature"]),
    ("ro_pirate_skeleton", "Brinebone Buccaneer", "A", "UB", "pirate", ["Undead"]),
    ("ro_poisonous_toad", "Venomwart Toad", "A", "BG", "frog", ["Poison"]),
    ("ro_pom_spider", "Pomhair Spider", "D", "G", "spider", ["Predator"]),
    ("ro_pope_guard", "Temple Doorwarden", "D", "W", "cleric", ["Human", "Guard"]),
    ("ro_pope_normal", "Sunlit Hierophant", "M", "WU", "cleric", ["Human", "Religious"]),
    ("ro_poporing", "Dewdrop Ooze", "A", "GW", "ooze", ["Small"]),
    ("ro_porcellio", "Spinecoil Isopod", "A", "G", "insect", ["Small"]),
    ("ro_queen_scaraba", "Queen of the Gilded Brood", "X", "WBG", "insect", ["Leader", "Flying"]),
    ("ro_quve", "Hollowlight Shade", "D", "UB", "shade", ["Nocturnal"]),
    ("ro_rafflesia_arnoldi", "Carrionbloom", "D", "GW", "plant", ["Nature"]),
    ("ro_ragged_zombie", "Tatterclad Zombie", "A", "B", "zombie", []),
    ("ro_raptice", "Veiltongue Chameleon", "A", "UG", "lizard", ["Sneaky"]),
    ("ro_rata", "Nutcache Scrapper", "A", "GW", "squirrel", ["Small"]),
    ("ro_raydric", "Hollow Oathkeeper", "M", "WU", "knight_undead", ["Spirit"]),
    ("ro_raydric_archer", "Hollow Oath Archer", "D", "W", "spirit", ["Archer", "Knight"]),
    ("ro_red_eruma", "Redcap Nibbler", "A", "RG", "fungus", ["Small"]),
    ("ro_repair_robot", "Tinkerwork Mender", "D", "U", "construct", ["Robot"]),
    ("ro_rideword", "Grimoire Devourer", "D", "UB", "construct", ["magical"]),
    ("ro_roda_frog", "Pondsong Frog", "A", "UG", "frog", ["Water"]),
    ("ro_rsx_event", "Clockwork Siegewalker", "M", "URW", "construct", ["Robot", "Large"]),
    ("ro_salamander", "Cinderscale Salamander", "D", "R", "lizard", ["Fire"]),
    ("ro_sasquatch", "Snowpeak Sasquatch", "D", "URG", "yeti", ["Snow", "Large"]),
    ("ro_savage", "Bristlehide Boar", "A", "RG", "beast", ["Wild"]),
    ("ro_scorpion", "Dunestinger Scorpion", "A", "R", "insect", ["Poison"]),
    ("ro_seal", "Floewalker Seal", "A", "WU", "sea", ["Snow", "Swimming"]),
    ("ro_seaweed", "Tanglekelp", "A", "U", "sea", ["Plant", "Water"]),
    ("ro_seeker", "Bloodwatch Seeker", "D", "UR", "horror", ["Flying"]),
    ("ro_shellfish", "Pearlmaw Clam", "A", "U", "sea", ["Swimming"]),
    ("ro_side_winder", "Sidewind Adder", "D", "G", "snake", ["Poison"]),
    ("ro_skeleton", "Barrow Skeleton", "A", "B", "skeleton", []),
    ("ro_skeleton_archer", "Barrow Bonebow", "D", "B", "skeleton", ["Archer"]),
    ("ro_skeleton_general", "Marshal of the Barrow Legion", "M", "RWB", "skeleton", ["Leader", "Knight"]),
    ("ro_skeleton_prisoner", "Chainbound Skeleton", "D", "B", "skeleton", []),
    ("ro_skeleton_sailor", "Drowned Deckhand", "A", "UB", "pirate", ["Undead"]),
    ("ro_skeleton_soldier", "Barrow Legionnaire", "D", "WB", "skeleton", ["Soldier"]),
    ("ro_skeleton_weak", "Rattling Bones", "A", "B", "skeleton", ["Small"]),
    ("ro_skeleton_weak_soldier", "Cracked Shieldbone", "A", "WB", "skeleton", ["Soldier"]),
    ("ro_skeleton_worker", "Deepvein Bonedigger", "A", "BR", "skeleton", ["Miner", "Subterranean"]),
    ("ro_skogul", "Nightwing Chooser", "M", "WUB", "angel", ["Flying", "Unholy"]),
    ("ro_spore", "Sporecap Shambler", "A", "BG", "fungus", []),
    ("ro_stem_worm", "Stalkroot Worm", "A", "G", "worm", ["Subterranean"]),
    ("ro_stone_shooter", "Rockthrower Oak", "D", "RGW", "treefolk", ["Nature"]),
    ("ro_stormy_knight", "Tempest Paragon", "X", "URW", "knight", ["Snow", "Leader"]),
    ("ro_succubus", "Crimson Temptress", "M", "BR", "demon", ["Flying"]),
    ("ro_tamruan", "Pitblade Reaver", "M", "BR", "demon", ["Warrior"]),
    ("ro_tarou", "Tallow Rat", "A", "B", "rat", ["Small"]),
    ("ro_tendrilrion", "Tendrilmane, the Pale Lion", "X", "GWU", "beast", ["Leader", "Legendary"]),
    ("ro_tengu", "Crimsonbeak Tengu", "M", "UR", "tengu", ["Flying"]),
    ("ro_thara_frog", "Blushback Frog", "A", "UG", "frog", []),
    ("ro_the_paper", "Scrollwraith", "D", "U", "spirit", ["Floating"]),
    ("ro_thief_bug", "Pilfer Beetle", "A", "UB", "insect", ["Thief", "Small"]),
    ("ro_thief_bug_female", "Hoarder Beetle", "D", "WBG", "insect", ["Thief"]),
    ("ro_thief_bug_male", "Jadeshell Beetle", "D", "UBG", "insect", []),
    ("ro_tikbalang", "Crossroads Tikbalang", "M", "BRG", "beast", ["Trickster"]),
    ("ro_tiyanak", "Wailing Changeling", "D", "B", "horror", ["Sneaky"]),
    ("ro_toad", "Bogbelly Toad", "D", "UG", "frog", []),
    ("ro_toucan", "Bramblebeak Toucan", "A", "G", "bird", ["Flying"]),
    ("ro_tri_joint", "Triplate Crawler", "A", "GW", "insect", []),
    ("ro_undead_knight_female", "Revenant Knight-Errant", "M", "WB", "knight_undead", []),
    ("ro_undead_knight_male", "Revenant Knight-Captain", "M", "WUB", "knight_undead", ["Leader"]),
    ("ro_ungoliant", "Mother of Webs", "X", "UBG", "spider", ["Leader"]),
    ("ro_valkyrie", "Valkyrie of the Last Field", "M", "W", "angel", ["Flying"]),
    ("ro_valkyrie_randgris", "Randgrith, Storm Shieldmaiden", "X", "RWB", "angel", ["Flying", "Legendary"]),
    ("ro_vanberk", "Ragged Hermit", "D", "RG", "warrior", ["Human", "Wild"]),
    ("ro_verit", "Gravehound", "A", "B", "zombie", ["Animal"]),
    ("ro_vitata", "Carapace Stalker", "D", "RG", "spider", []),
    ("ro_wakwak", "Nightwing Bat", "A", "B", "bat", ["Flying", "Nocturnal"]),
    ("ro_wanderer", "Ronin of the Ashen Road", "M", "RW", "samurai", ["Wandering"]),
    ("ro_wild_rose", "Rosethorn Prowler", "D", "RGW", "cat", ["Predator"]),
    ("ro_willow", "Hollow Willow", "A", "BG", "treefolk", []),
    ("ro_wind_ghost", "Galewrapped Specter", "M", "GWU", "spirit", ["Wind"]),
    ("ro_wish_maiden", "Wishgiver Seraph", "X", "GWU", "angel", ["Flying", "Holy"]),
    ("ro_wolf", "Frostpelt Wolf", "A", "GW", "wolf", ["Snow"]),
    ("ro_wood_goblin", "Blossom Sapling", "A", "GW", "treefolk", ["Small"]),
    ("ro_wootan_fighter", "Skullcap Brawler", "D", "RG", "ape", ["Warrior"]),
    ("ro_wootan_shooter", "Slingshot Ape", "D", "R", "ape", ["Archer"]),
    ("ro_wormtail", "Wormtail Sprout", "A", "G", "plant", ["Small"]),
    ("ro_wounded_morroc", "The Maimed Demon-King", "X", "UBR", "demon", ["Leader"]),
    ("ro_wraith", "Gloomshroud Wraith", "D", "WU", "wraith", ["Nocturnal"]),
    ("ro_wraith_dead", "Deathshroud Wraith", "M", "WB", "wraith", []),
    ("ro_zealotus", "Zealot of the Crimson Lash", "X", "RWB", "cleric", ["Human", "Leader"]),
    ("ro_zenorc", "Cultist of the Tusk", "A", "RWB", "orc", ["Cleric"]),
    ("ro_zipper_bear", "Ironclaw Bear", "D", "G", "beast", ["Wild"]),
    ("ro_zombie", "Shambling Corpse", "A", "B", "zombie", []),
    ("ro_zombie_guard", "Cryptguard Zombie", "D", "UB", "zombie", ["Guard"]),
    ("ro_zombie_master", "Cadaver Lord", "X", "UBR", "zombie", ["Leader", "Necromancer"]),
    ("ro_zombie_prisoner", "Shackled Dead", "D", "B", "zombie", []),
    ("ro_zombie_slaughter", "Butcher of the Dead", "M", "BR", "zombie", ["Warrior"]),
    # ---------------------------------------------------------------- render sheets (73)
    ("gen_dragon", "Ashen Spinewyrm", "M", "BRG", "dragon", ["Flying"]),
    ("gen_alien_monster", "Voidmaw Stalker", "M", "UBR", "horror", ["Predator"]),
    ("gen_alien_fungus", "Sporeshell Crawler", "D", "UG", "fungus", []),
    ("gen_alien_garb", "Crimson Burrower", "D", "R", "insect", ["Subterranean"]),
    ("gen_alien_lump", "Fleshlump Horror", "D", "U", "horror", []),
    ("gen_alien_wretch", "Violet Wretch", "D", "U", "horror", []),
    ("gen_android_walker", "Ironstride Construct", "M", "WUR", "construct", ["Large"]),
    ("gen_angel", "Dawnblade Angel", "M", "W", "angel", ["Holy"]),
    ("gen_ankylosaurus", "Shellback Ankylosaur", "D", "RGW", "dinosaur", ["Large"]),
    ("gen_arcane_witch", "Tidecaller Witch", "X", "U", "wizard", ["Human"]),
    ("gen_arch_angel", "Archangel of the Gilded Dawn", "X", "W", "angel", ["Holy", "Leader"]),
    ("gen_armored_orc", "Blazeplate Orc", "D", "RW", "orc", ["Warrior"]),
    ("gen_astral_dragon", "Astral Wyrm", "X", "UBR", "dragon", ["Flying", "Mythical"]),
    ("gen_azure_executioner", "Azure Headsman", "M", "URW", "warrior", ["Human"]),
    ("gen_banshee", "Keening Banshee", "D", "WU", "spirit", ["Ghost"]),
    ("gen_barbarian_cyclops2", "Cyclops of the Scorched Hills", "M", "RG", "giant", ["Large"]),
    ("gen_blood_reaper", "Crimson Reaper", "M", "B", "vampire", []),
    ("gen_bloody_mary", "Bloodveil Countess", "M", "RWB", "vampire", ["Leader"]),
    ("gen_chinese_warlords", "Golden Glaive Warlord", "M", "RGW", "samurai", ["Leader"]),
    ("gen_crawling_zombie", "Crawling Cadaver", "A", "B", "zombie", []),
    ("gen_crimson_dragon", "Crimson Skywyrm", "M", "URW", "dragon", ["Flying"]),
    ("gen_cruststrider", "Cruststrider", "D", "RGW", "beast", ["Large"]),
    ("gen_dark_dragon", "Umbral Dragon", "X", "WUB", "dragon", ["Flying"]),
    ("gen_dark_overlord", "Overlord of Black Pinions", "X", "RWB", "demon", ["Flying", "Leader"]),
    ("gen_devil_empress", "Devil Empress", "X", "UBR", "devil", ["Leader"]),
    ("gen_dracon_medusa", "Azure Gorgon", "M", "UB", "gorgon", ["Flying"]),
    ("gen_drago_demon", "Dragonwing Demon", "M", "UBR", "demon", ["Flying"]),
    ("gen_dutchess_succubus", "Duchess of Thorns", "M", "WUB", "demon", ["Flying"]),
    ("gen_elephantman", "Tuskbound Loxodon", "D", "GW", "loxodon", ["Warrior"]),
    ("gen_executioner", "Grim Executioner", "D", "R", "warrior", ["Human"]),
    ("gen_fang_monster", "Fangmaw Ravager", "D", "RG", "horror", ["Predator"]),
    ("gen_fanged_behemoth", "Fanged Behemoth", "M", "G", "beast", ["Huge"]),
    ("gen_female_orc", "Tuskmaiden Skirmisher", "D", "RG", "orc", ["Warrior"]),
    ("gen_female_zombie", "Grave-Tattered Bride", "A", "WB", "zombie", []),
    ("gen_female_zombie_2", "Plague Ghoul", "A", "B", "zombie", ["Poison"]),
    ("gen_flying_shark", "Skyreef Shark", "D", "U", "shark", ["Flying"]),
    ("gen_free_game_assetes", "Ironhammer Brute", "M", "R", "giant", ["Warrior"]),
    ("gen_furhorn_wyvern_art", "Furhorn Wyvern", "D", "WU", "drake", ["Flying"]),
    ("gen_gold_dragon", "Aurelian Dragon", "X", "RGW", "dragon", ["Flying", "Mythical"]),
    ("gen_greater_spawn", "Brood Spawn", "M", "UBG", "horror", ["Swarm"]),
    ("gen_green_dragon", "Verdant Wyrm", "X", "URG", "dragon", ["Flying"]),
    ("gen_griffin", "Stormcrag Griffin", "D", "W", "griffin", ["Flying"]),
    ("gen_harpy", "Talonborn Harpy", "D", "UB", "harpy", ["Flying"]),
    ("gen_horror_faun", "Horror Faun", "D", "RG", "satyr", []),
    ("gen_inferno_dragon", "Inferno Drake", "M", "R", "dragon", ["Flying", "Fire"]),
    ("gen_lava_trigog", "Magmaback Crawler", "D", "R", "lizard", ["Fire"]),
    ("gen_lion_1", "Sunmane Lion", "D", "GW", "cat", ["Wild"]),
    ("gen_lizard_supremus", "Vinewing Lizardlord", "M", "URG", "lizard", ["Flying"]),
    ("gen_lizardragon", "Bonewhite Lizardragon", "M", "W", "dragon", ["Flying"]),
    ("gen_magma_dragon", "Magma Dragon", "X", "UR", "dragon", ["Flying", "Fire"]),
    ("gen_magma_ogre", "Magma Ogre", "M", "RW", "ogre", ["Fire"]),
    ("gen_magnum_shell_wyrm", "Shellplate Wyrm", "D", "GWU", "beast", ["Large"]),
    ("gen_mawjaw_drake", "Mawjaw Drake", "D", "UR", "drake", ["Flying"]),
    ("gen_megamouth_wyrm", "Megamouth Wyrm", "D", "UR", "drake", []),
    ("gen_minimon", "Pinkhide Gorger", "A", "R", "beast", []),
    ("gen_ogre_mother", "Ogre Matriarch", "M", "RGW", "ogre", ["Leader"]),
    ("gen_parasitic_zombie_2", "Parasite-Ridden Husk", "D", "UB", "zombie", ["Horror"]),
    ("gen_quadracepsis", "Four-Maw Horror", "M", "UBG", "horror", []),
    ("gen_rolly_tusker_1", "Rolling Tusker", "D", "G", "beast", []),
    ("gen_sabertusk_dragon", "Sabertusk Dragon", "X", "URG", "dragon", ["Flying"]),
    ("gen_serplegs", "Serpleg Stalker", "D", "U", "horror", []),
    ("gen_serratongue", "Serratongue", "D", "RG", "beast", ["Predator"]),
    ("gen_she_devil_succubus", "Scarlet Temptress", "M", "R", "devil", ["Flying"]),
    ("gen_shinto_scythe", "Shrine Scythe-Dancer", "M", "URW", "monk", ["Human"]),
    ("gen_shredder_monger", "Shredmaw Monger", "D", "RG", "beast", ["Predator"]),
    ("gen_skull_mage", "Skullrobe Necromancer", "M", "WUB", "wizard", ["Necromancer", "Undead"]),
    ("gen_slash_monger_1", "Slashmaw Monger", "D", "R", "beast", ["Predator"]),
    ("gen_t_rex", "Tyrant Rex", "X", "RGW", "dinosaur", ["Huge"]),
    ("gen_void_dragon", "Void Dragon", "X", "WUB", "dragon", ["Flying"]),
    ("gen_whalerhustler", "Tidetusk Brute", "D", "URG", "ape", ["Water"]),
    ("gen_zombie", "Rotwalker", "A", "B", "zombie", []),
    ("gen_", "Bloodwing Dragon", "M", "RWB", "dragon", ["Flying"]),
    ("gen_white", "Mossback Dragon", "M", "GWU", "dragon", ["Flying"]),
]
